/**
 * contecst
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.10
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CollectionPath = 'events' | 'users' | 'youtubeVideos';

export const CollectionPath = {
    Events: 'events' as CollectionPath,
    Users: 'users' as CollectionPath,
    YoutubeVideos: 'youtubeVideos' as CollectionPath
};

