/**
 * contecst
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionPath } from './collectionPath';


export interface Document { 
    collection: CollectionPath;
    id: string;
    /**
     * Document data (for use with `DocumentReference.set()`) consists of fields mapped to values.
     */
    data?: { [key: string]: any; };
}
export namespace Document {
}


