/**
 * contecst
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.25
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CollectionPath } from './collectionPath';


export interface NiaxTableQueryCollectionPath { 
    limit?: number;
    cols?: string;
    resourceId?: string;
    resourceName: CollectionPath;
    rowsPageToken?: string;
}
export namespace NiaxTableQueryCollectionPath {
}


