/**
 * contecst
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UserRole = 'guest' | 'base' | 'admin';

export const UserRole = {
    Guest: 'guest' as UserRole,
    Base: 'base' as UserRole,
    Admin: 'admin' as UserRole
};

